module.exports = (app, router) => {
  require('./acceder.js')(app, router)
  require('./configuraciones.js')(app, router)
  require('./cotizaciones.js')(app, router)
  require('./fletes.js')(app, router)
  require('./frecuencia.js')(app, router)
  require('./generico.js')(app, router)
  require('./itemsMercaderias.js')(app, router)
  require('./itemsServicios.js')(app, router)
  require('./mediosPagos.js')(app, router)
  require('./mercaderias.js')(app, router)
  require('./mercaderiasGrupos.js')(app, router)
  require('./mercaderiasMarcas.js')(app, router)
  require('./mercaderiasSubGrupos.js')(app, router)
  require('./monedas.js')(app, router)
  require('./pagos.js')(app, router)
  require('./personas.js')(app, router)
  require('./presupuestos.js')(app, router)
  require('./seguros.js')(app, router)
  require('./servicios.js')(app, router)
  require('./serviciosGrupos.js')(app, router)
  require('./status.js')(app, router)
  require('./usuarios.js')(app, router)
};
